### ISSUE TITLE
Race condition when saving score in 60 seconds mode

### ISSUE THREAD

**Issue by Self-Perfection** [walokra/colordots#2]
Once I have ended up in following state
![screenshot-24-07-15-10-03-33_50](https://cloud.githubusercontent.com/assets/3757038/8890541/70f9d9d0-330d-11e5-9e88-b7c1099ddf25.png)
Note that game window shows score 184, but score board have recorded score 181.

I suppose the app processed events in following order:
1. Time is up - record score
2. Process current move
3. Stop game & display score board

This wrong, stopping game should be atomic.

**Comment by walokra** [comment]
Thanks for reporting this issue. Timer and processing moves didn't play nicely together.

**Comment by Self-Perfection** [comment]
```
$ rpm -q harbour-colordots
harbour-colordots-0.4.0-1.armv7hl
```

The issue is not fixed. I got similar state after 60s game
![screenshot-16-08-24-10-34-25_50](https://cloud.githubusercontent.com/assets/3757038/17922596/e1c7f2da-69f0-11e6-845d-36a6ecf13b3c.png)
