### ISSUE TITLE
Occasionally wrong shape is used

### ISSUE THREAD

**Issue by Self-Perfection** [walokra/colordots#3]
Once I got stuck in 60 seconds mode and could not make any move. But I was quick enough to save a screenshot:

![screenshot-24-07-15-22-52-34_50](https://cloud.githubusercontent.com/assets/3757038/8890599/fb31ef24-330e-11e5-8c0e-07e5ab08fcf2.png)

Please examine top right corner of game board. There green dots in star and diamond shapes. It seems that I looked for identical shapes and missed the single possible move because of shape mismatch.

My guess: the app changed dot color after it was generated to make at least one move possible but forgot to change its shape. Ewww.

IMHO, regenerating of whole game field and giving a player a bunch of bonus points is a better handling of "no moves left" case.

**Comment by walokra** [comment]
Thanks for reporting this issue. The field is now refilled if there's no possible moves left. No bonus points though :)
