### ISSUE TITLE
aarch64 builds

### ISSUE THREAD

**Issue by poetaster** [walokra/colordots#4]
I've just gone ahead in my private space:
https://build.sailfishos.org/package/show/home:poetaster:colordots/colordots

If you wish I can push them to chum so that people can install them normally?

**Comment by walokra** [comment]
Thanks for the iniative. 

Colordots is already on OBS (https://build.sailfishos.org/package/show/home:walokra:sailfishos/colordots) but as noted it lacks the aarch64 build. I will check how I get the architechture to build and promote it.
